name: Docker Image CI

on:
  push:
    branches:
      - master
      - main
    paths:
      - "bin/entry_point.sh"
      - "Dockerfile"
      - "Gemfile"
      - "Gemfile.lock"
      - "package.json"
      - "package-lock.json"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'alshedivat'

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0

      - name: Buildx
        uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c # v3.1.0

      - name: Login
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: amirpourmand/al-folio
