name: Docker Slim

#Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

# on:
#   push:
#     branches:
#       - 'master'

jobs:
  build:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow
    if: ${{ github.event.workflow_run.conclusion == 'success' }} and github.repository_owner == 'alshedivat'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Login
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: update docker-compose
        shell: bash
        run: |
          sed -i "s|\.:|${{ github.workspace }}:|g" ${{ github.workspace }}/docker-compose.yml
          cat ${{ github.workspace }}/docker-compose.yml

      - uses: kitabisa/docker-slim-action@beb11ec385b938955a83a299683d15245a6fe06c # v1.0.3
        env:
          DSLIM_PULL: true
          DSLIM_COMPOSE_FILE: ${{ github.workspace }}/docker-compose.yml
          DSLIM_TARGET_COMPOSE_SVC: jekyll
          DSLIM_CONTINUE_AFTER: signal
        with:
          target: amirpourmand/al-folio
          tag: "slim"

      # Push to the registry
      - run: docker image push amirpourmand/al-folio:slim
